name: test-makefile

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://pandoc/core:2
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Ablage erstellen ...
        run: mkdir Ablage
      - name: blabla
        run: |
          ls -la
          apt-get update
          apt-get install make -y
          make --version

# name: test-using-makefile
#
# on: push
#
# jobs:
#   generate_website:
#     runs-on: ubuntu-latest
#     container:
#       image: docker://pandoc/core:2
#       options: --entrypoint=sh
#     steps:
#       - name: Repository Checkout ...
#         uses: actions/checkout@v2
#
#       - name: Ablage erstellen ...
#         run: mkdir Ablage
#
#       - name: test ...
#         run: ls -la && apt-get -y install make && make
#
#       - name: Uhrzeit an Zeitzone anpassen ...
#         uses: zcong1993/setup-timezone@master
#         with:
#           timezone: Europe/Berlin
#
#       - name: Zeitstempel erstellen ...
#         run: echo "MWDW_TIMESTAMP=`date +'%Y-%m-%d--%H-%M-%S'`" >> $GITHUB_ENV
#
#       - name: Datei zum internen Download bereitstellen ...
#         uses: actions/upload-artifact@master
#         with:
#           name: Gestaltungsrichtlinien-${{ env.MWDW_TIMESTAMP }}
#           path: Ablage
