name: generate website ... RVW-Mitteilungen-Werkzeuge

on: push

jobs:
  generate_website:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout ...
        uses: actions/checkout@v2

      - name: Ablage erstellen ...
        run: mkdir Ablage

      - name: Uhrzeit an Zeitzone anpassen ...
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin

      - name: Zeitstempel erstellen ...
        run: echo "MWDW_TIMESTAMP=`date +'%Y-%m-%d--%H-%M-%S'`" >> $GITHUB_ENV

      - name: Pandoc/LaTeX holen, anpassen und Umwandlung ausführen ...
        uses: docker://pandoc/core:2
        with:
          entrypoint: /bin/sh
        run: make
          # args: >-
          #   -c "
          #    make
          #   "

      - name: Datei zum internen Download bereitstellen ...
        uses: actions/upload-artifact@master
        with:
          name: Gestaltungsrichtlinien-${{ env.MWDW_TIMESTAMP }}
          path: Ablage
